### ISSUE TITLE
[cleaner] The regex fails to match if mac/IPv6 is at start position 

### ISSUE THREAD

**Issue by NikhilKakade-1** [sosreport/sos#2829] opened 2022-01-21 12:22 UTC
The current regex fails to obscure the mac or IPv6 at the start of the line.
https://github.com/sosreport/sos/blob/105075539e0cf7525657aa2004ca6503edf6e6b2/sos/cleaner/parsers/mac_parser.py#L26
The regex should be:

`(([^:|-])?([0-9a-fA-F]{2}([:-])){5}([0-9a-fA-F]){2}(.)?(\s|$|\W))`

**Before:**

**NOT Matching**

<img width="816" alt="Screenshot 2022-01-21 at 2 01 34 PM" src="https://user-images.githubusercontent.com/66179696/150525189-3707d304-8aac-4897-97ea-e5c620a33e62.png">

**Matches only If we do have character at start:**

<img width="816" alt="Screenshot 2022-01-21 at 2 01 42 PM" src="https://user-images.githubusercontent.com/66179696/150525348-966598df-d567-4aef-8aae-788280868cce.png">

> ### FIX

<img width="1651" alt="Screenshot 2022-01-21 at 5 47 33 PM" src="https://user-images.githubusercontent.com/66179696/150525860-e7d8a0b9-5e0e-4ce7-b93e-fe28fe997954.png">

@TurboTurtle what's your suggestion? am I missing something here?

**Comment by TurboTurtle** [comment] 2022-01-21 16:10
This looks like a valid and correct fix to me, yes.

If you open a PR with this change our test suite will verify that we're not causing a regression here with our current expectation of mac obfuscations.

**Comment by UcanD0** [comment] 2022-01-24 09:12
@TurboTurtle 
I have raised PR could you please, look into it?

**Comment by TurboTurtle** [comment] 2022-01-25 16:43
Closing per #2833

**Closed by TurboTurtle** 2022-01-25 16:43 UTC
