### ISSUE TITLE
SOScleaner integration

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#1557] opened 2019-02-04 17:30 UTC
Any plan to integrate SOSCleaner[1] into sosreport project ?
I think some user would appreciate to have the capability to obfuscate sensible data such as hostname and IP.

I see a discussion has been started 5 years ago on issue #311, but it doesn't seemed to go anywhere.

I'm taking the chance to restart the discussion.

[1] https://github.com/jduncan-rva/soscleaner

Regards,
Eric

**Comment by bmr-cymru** [comment] 2019-02-04 17:48
We've always been open to more sanitisation in the main `sos` project, but we have a strict rule that we don't compromise the support data - so any transformation (e.g. of IP addresses, names etc.) **must** preserve all the original relationships, such that it is useful to a support engineer to diagnose, and so that the customer can implement fixes (since they hold the "Rosetta Stone" decoder-ring needed to put it back together).

This was not the case, at least with IP address obfuscation in `SOSCleaner` in the past - it's also not as simple as our just including the script in the source tree. It would need considerable work to make it use `sos` APIs etc, and to avoid all the unpack/repack work that it is currently forced to do.

**Comment by TurboTurtle** [comment] 2020-01-28 20:47
Closing as a duplicate of #311, which has been tagged for `4.0` planning discussion.

**Closed by TurboTurtle** 2020-01-28 20:47 UTC
