### ISSUE TITLE
Wrong information collected by ethtool -k

### ISSUE THREAD

**Issue by crackcodecamp** [sosreport/sos#1534] opened 2019-01-10 09:16 UTC
While collecting `ethtool -k` sometimes it collected error message or wrong information.

For e.g. Data collected in file name `ethtool_-k_eth1`

`Cannot get device udp large send offload settings: Operation not supported
Offload parameters for eth1:
rx-checksumming: on
tx-checksumming: on
scatter-gather: on
tcp segmentation offload: on
udp fragmentation offload: off
generic segmentation offload: off
generic-receive-offload: on`

Can anyone look into this issue and provide appropriate information or fix patch?

**Comment by crackcodecamp** [comment] 2019-01-10 09:31
Yes I tried several times `ethtool -k eth1` it gives good output.

**Comment by pmoravec** [comment] 2019-01-10 10:42
And if you run:

    LC_ALL=C timeout 300s ethtool -k eth1

(I forget all commands are run under the timeout cmd and using that locale, by default, and that *can* play a role)

Optionally, can you provide "sosreport -o network -vvv --batch" output together with the tarball created (e.g. to my mail)?

**Comment by bmr-cymru** [comment] 2019-01-10 14:18
Not sure I understand what "Operation not supported" has to do with timeouts?

This is an `EOPNOTSUPP` errno status from a system call. In other words the kernel is telling us that the device we have issued the `ioctl` for does not support that `ioctl` command.

It's very difficult to see why this would be different when the command is run from the terminal vs. from `sos` - in either case, the problem is happening between the `ethtool` command from the `ethtool` package, and the kernel and network drivers that fulfil the request.

This should be reported to the respective projects as it does not appear to be a bug in `sos` itself.

**Comment by bmr-cymru** [comment] 2019-01-10 14:20
One exception would be if some form of partitioning or container were in use here, such that the context in which `sos` runs lacks privileges to call this `ioctl` command, however that seems very unlikely as that would normally result in a permission denied type of error return.

**Comment by TurboTurtle** [comment] 2020-11-20 17:15
Closing this as it does not seem to be directly related to an sos fault.

**Closed by TurboTurtle** 2020-11-20 17:15 UTC
