### ISSUE TITLE
[pcp] improve Performance Co-Pilot support

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#430] opened 2014-11-12 16:55 UTC
via fche in RHBZ#1163423:

```
The sosreport pcp plugin should also:

- include $PCP_LOG_DIR/pmmgr/ subdirectories for selecting candidate archives
- sort candidate archives by age for selection so as to favour recent ones
  for sosreport inclusion
- ensure archive .[0-9]*/.index/.meta files get selected all-or-none
- compensate for high compressibility of archives (by pre-compressing, or
  assuming some 90%+ rate when picking pcplog_totalsize.
```

**Comment by jcastill** [comment] 2017-09-10 10:38
This is a very interesting one for me. The files in $PCP_LOG_DIR/pmmgr are created byt he 'pmmgr' tool, which belongs to an extra rpm: pcp-manager.x86_64. What this tool does is receive pcp logs from other servers in the network, and stores them locally in the $PCP_LOG_DIR/pmmgr directory . The problem is, from what I'm seeing, that for each discovered host we'll have a;

	$PCP_LOG_DIR/pmmgr/<hostname>/<pcp log files>

I.e. I've just configured a server and client, and this is the layout:

	# ll /var/log/pcp/pmmgr/
	total 8
	-rw-r--r--. 1 pcp pcp 765 Sep 10 11:16 pmmgr.log
	-rw-r--r--. 1 pcp pcp 109 Sep 10 09:53 pmmgr.log.prev
	drwxr-xr-x. 2 pcp pcp 190 Sep 10 11:16 vm-169.gsslab.fab.redhat.com
	# ll -h /var/log/pcp/pmmgr/vm-169.gsslab.fab.redhat.com/
	total 5.9M
	-rw-r--r--. 1 pcp pcp 3.9M Sep 10 11:27 archive-20170910.101613.0
	-rw-r--r--. 1 pcp pcp  912 Sep 10 11:27 archive-20170910.101613.index
	-rw-r--r--. 1 pcp pcp 148K Sep 10 11:25 archive-20170910.101613.meta
	-rw-r--r--. 1 pcp pcp 3.8K Sep 10 11:16 config.pmie
	-rw-r--r--. 1 pcp pcp  25K Sep 10 11:16 config.pmlogger
	-rw-r--r--. 1 pcp pcp  486 Sep 10 11:18 pmie.log
	-rw-r--r--. 1 pcp pcp  15K Sep 10 11:16 pmlogger.log

My point here is that basically we may be getting lots of logs from servers we are not interested in - that is, if i'm understanding fche and he actually wants to collect the content of these subdirs. 
Perhaps a better solution would be to collect a 'ls -laR /var/log/pcp/pmmgr/' like we do for /sys/block and /dev ? And to complement the list of files with the config files in /etc/pcp/pmmgr/ .

**Comment by pmoravec** [comment] 2017-09-10 17:34
Good suggestion - when collecting sosreport for node/server A, we should not be interested in details / logs from server B - maybe just about details that can (significantly) affect node/server A behaviour, if there is any.

About the proposed change - shall not we also collect files (not dirs) under `$PCP_LOG_DIR/pmmgr/` directory? Like `pmmgr.log*` there?

**Comment by fche** [comment] 2017-09-12 15:16
`pmmgr` is a bit of a red herring.  pmmgr can be easily run as local-host-only, and `service pmlogger` cron-driven pmloggers can be fairly easily be run as remote-host-only.  We'd have to analyze the directory/file names a little (or the archive log-label header via `pmloglabel -l`) to identify data belonging only to the local server.

**Comment by bmr-cymru** [comment] 2017-09-12 16:26
We should also consider the case where the user actually *wants* to include non-local PCP data in the report. This might not be the most common use-case, but I can see reasons why someone may want to do it. I think it would be fine to hide this behind a plugin option (or even `--all-logs`), since it could greatly increase the amount of PCP data we collect.

**Comment by jcastill** [comment] 2017-09-14 08:05
OK so behaviour can be:
- By default, look for a directory with local host name in $PCP_LOG_DIR/pmmgr. If found, then add it to sos. If not, then don't gather anything in that directory.
- If option --all-logs (or similar, and the scope can be for the plugin or global) is used, then collect the whole content of $PCP_LOG_DIR based on the rules previously specified by fche. 

Did I miss or misinterpret anything? If not, hopefully I'll have something you guys can review soon.

**Comment by pmoravec** [comment] 2017-09-14 09:06
Sounds good.

**Comment by TurboTurtle** [comment] 2020-04-02 14:49
I believe this should have been closed with the current state of the plugin, but no individual commit included a reference here.

Closing this as resolved, if there are still requests for the `pcp` plugin please open a new Issue or PR.

**Closed by TurboTurtle** 2020-04-02 14:49 UTC
