### ISSUE TITLE
RFE: Provide a way to globally exclude paths from being collected

### ISSUE THREAD

**Issue by rmetrich** [sosreport/sos#2263] opened 2020-10-08 10:17 UTC
This is a continuation of PR #2262.

With current code, it's not possible to exclude a path using `add_forbidden_path` globally. I think having such functionality would be nice as a workaround for issues, e.g. the object of PR #2262.

**Comment by bmr-cymru** [comment] 2020-10-08 10:23
This is a dupe of #316 - @adam-stokes already did some work for this in pull request #354. For some reason that was closed without being merged. It should be fairly easy to resurrect the changes and forward port to current (although I would suggest changing `files_blacklist` to something like `global_forbidden_paths`).

**Comment by TurboTurtle** [comment] 2020-10-08 13:59
I think this is two-pronged. Both the policy-level work mentioned by @bmr-cymru, and a cmdline option to allow adhoc exclusions.

@rmetrich am I understanding that correctly? Or are you just referring to policy-level forbids?

**Comment by TurboTurtle** [comment] 2020-11-20 17:08
I believe this has been satisfied via 55ca9a8 - which added the `--skip-files` and `--skip-cmds` options. If this is not sufficient, please feel free to reopen this issue.

**Closed by TurboTurtle** 2020-11-20 17:08 UTC
