### ISSUE TITLE
Release planning for 3.8.1 or 3.9?

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#1892] opened 2019-12-12 18:22 UTC
I'd like to start planning for when we are going to make the next release and what if anything additional we should aim to have for it.

If it's just making a summary and tagging it - I'm happy to run with that.  Thanks!

**Comment by slashdd** [comment] 2019-12-12 18:39
Wearing my Debian/Ubuntu maintainer hat and considering focal being our next LTS (long term support), obviously, I would like to have a sosreport release which include the interesting stuffs that happens after 3.8 release, instead of cherry-pick them ;)

**Comment by pmoravec** [comment] 2019-12-13 15:15
We aimed to release a sos version every 6 months, while 3.8 went out  Aug 27th. What is exactly half a year before 20.04 LTS freeze :)

Wearing my Fedora hat, 3.9 release in approx. mid Feb would fit some RHEL deadline as well.

Looking to @bmr-cymru and @TurboTurtle for further comments..?

**Comment by TurboTurtle** [comment] 2019-12-16 14:36
Mid-Feb 3.9 release sounds good to me. From there, I'd really like to get moving on sos-4.0 planning/work.

**Comment by slashdd** [comment] 2020-01-27 19:42
Are we still good for releasing 3.9 mid-february ? Any day in mind ?

Just as a reminder ... our Ubuntu next LTS (long term support) release (focal/20.04) will enter it's feature freeze on Feb 27th. It would help a lot if we can manage to get the 3.9 release ready before that Ubuntu due date.

**Comment by slashdd** [comment] 2020-01-27 19:43
For the reference:
https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule

**Comment by pmoravec** [comment] 2020-01-28 08:29
Thanks for reminder, I was just about to write down a list of pending PRs that "must" go to the release - please provide yours if there is any.

https://github.com/sosreport/sos/pull/1923 (regression since 3.8)
https://github.com/sosreport/sos/pull/1911 (nice feature we shall have in 3.9)
https://github.com/sosreport/sos/pull/1910 (better logging)
https://github.com/sosreport/sos/pull/1909 (fixes some "stuck" commands)
https://github.com/sosreport/sos/pull/1908 (dont truncate sar data)
https://github.com/sosreport/sos/pull/1907 (bpftool to a dedicated plugin)
- plus any simple PRs pending, as usual

Cc @bmr-cymru and @TurboTurtle for reviews of above PRs.

**Comment by TurboTurtle** [comment] 2020-01-28 18:19
Agreed, that looks good for finishing out a 3.9 release.

For #1911 - I'd really like @bmr-cymru's sign off, that way we have all the maintainers on that one

For #1907 and #1923 I think we need to decide which way we're going with `bpftool` - either a dedicated plugin or not. I personally think a dedicated plugin makes sense here, but I understand the argument for keeping the calls split across existing ones.

If we decide to keep the calls spread, then #1923 would need to update to match the changes in #1907 that were carried from the original #1902, where we stop opening the archived collection file for reading the IDs, and just use the `output` element from `collect_cmd_output()`.

**Comment by BryanQuigley** [comment] 2020-01-28 22:13
I'm discussing internally how we could rewrite the Juju ones
Issues #1653,   Current PR (but all needs revisions): #1670, #1671, #1672 

I'll review for others I want to be part of 3.9 on Thursday.

**Comment by pmoravec** [comment] 2020-02-09 12:06
Current status:
- upstream bits tested by me on a variety systems, no issue found \o/
- pending PRs to review & merge:
  - #1911 Allow automatic uploading ..
  - #1890 [archive] handle OSErrors
  - #1923 Collect bpftool [map|prog] in both formats (in conflict with #1907)
  - #1907 bpftool plugin (in conflict with #1923)
- pending PRs to update before merging:
  - #1670 juju 2.0 support (sudo -> runuser?)
  - #1671 juju_controller (Bryn's feedback)
  - #1672 juju_machine (`call_ext_prog` deprecated)

Let have those fixed&merged till Wed 12th, run any testing one wants, fix just issues from those testing and do the release on Fri 14th?

**Comment by slashdd** [comment] 2020-02-11 21:20
As a fyi, a simplify version of the juju plugin refactoring can be found here : #1935 

Replacing the following PRs:

#1670 juju 2.0 support (sudo -> runuser?)
#1671 juju_controller (Bryn's feedback)
#1672 juju_machine (call_ext_prog deprecated)

**Comment by slashdd** [comment] 2020-02-12 17:52
Far from me the idea to add more load, but since they should be trivial to review and would be useful to help our engineering support team at Canonical. Could you please try to approve the following to be part of 3.9 ? : 

#1942 
#1941 

There is a ceph plugin PR also on the way that should be ready in a couple of hours, that I would also request a special attention before 3.9 if possible.

I will keep you posted on the ceph PR progress.

Thanks a bunch !

**Comment by hillpd** [comment] 2020-02-13 18:04
The ceph plug-in update is ready for review:

#1947

**Comment by slashdd** [comment] 2020-02-14 13:32
Good day ! 
Are we still on track to release sosreport 3.9 today as originally stated ?

**Comment by bmr-cymru** [comment] 2020-02-14 15:30
> Are we still on track to release sosreport 3.9 today as originally stated ?

So far so good - I have a couple more things to review and merge but that's still the plan.

**Comment by slashdd** [comment] 2020-02-14 16:32
@bmr-cymru 
Did you guys notice the issue #1949 

I can workaround it in many way for Ubuntu, but would be curious to know where you stand on that topic that used to be dealt with in the past and reverted for some reasons.

**Comment by slashdd** [comment] 2020-02-14 17:07
Correction on my above statement, it seems like there was a PR that got closed, and I quickly assume it was merged, but after verificaiton it doesn't seemed that it got merged see #759

**Comment by TurboTurtle** [comment] 2020-02-17 16:55
sos-3.9 has been released, closing this issue.

We can continue ongoing requests in a sos-4.0 discussion issue thread that I will be opening shortly.

**Closed by TurboTurtle** 2020-02-17 16:55 UTC
