### ISSUE TITLE
[hpasm] hpasmcli commands timeout

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#559] opened 2015-05-05 11:43 UTC
In certain situations, hpasmcli commands get timeouted. The reason is some flaw in python<->timeout<->hpasmcli communication, as:

```
# timeout 10s hpasmcli -s "show server" | wc -l
42

# python -c "import os; os.system('timeout 10s hpasmcli -s \'show server\'')" | wc -l
< processes stopped >
```

**Comment by bmr-cymru** [comment] 2015-10-16 15:09
The problem can b reproduced by running hpasm under strace (since that yields a similar environment in terms of TTY and signal behaviour as running from python):

```
# strace timeout 20s hpasmcli -s 'show asr'
execve("/usr/bin/timeout", ["timeout", "20s", "hpasmcli", "-s", "show asr"], [/* 25 vars */]) = 0
brk(0)                                  = 0x124c000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa5159b9000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=45950, ...}) = 0
mmap(NULL, 45950, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fa5159ad000
close(3)                                = 0
open("/lib64/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\"\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=44088, ...}) = 0
mmap(NULL, 2128952, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fa515591000
mprotect(0x7fa515598000, 2093056, PROT_NONE) = 0
mmap(0x7fa515797000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6000) = 0x7fa515797000
close(3)                                = 0
open("/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240l\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=141616, ...}) = 0
mmap(NULL, 2208864, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fa515375000
mprotect(0x7fa51538b000, 2097152, PROT_NONE) = 0
mmap(0x7fa51558b000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x16000) = 0x7fa51558b000
mmap(0x7fa51558d000, 13408, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fa51558d000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\34\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=2107760, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa5159ac000
mmap(NULL, 3932736, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fa514fb4000
mprotect(0x7fa51516a000, 2097152, PROT_NONE) = 0
mmap(0x7fa51536a000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1b6000) = 0x7fa51536a000
mmap(0x7fa515370000, 16960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fa515370000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa5159ab000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa5159a9000
arch_prctl(ARCH_SET_FS, 0x7fa5159a9740) = 0
mprotect(0x7fa51536a000, 16384, PROT_READ) = 0
mprotect(0x7fa51558b000, 4096, PROT_READ) = 0
mprotect(0x7fa515797000, 4096, PROT_READ) = 0
mprotect(0x60b000, 4096, PROT_READ)     = 0
mprotect(0x7fa5159ba000, 4096, PROT_READ) = 0
munmap(0x7fa5159ad000, 45950)           = 0
set_tid_address(0x7fa5159a9a10)         = 20808
set_robust_list(0x7fa5159a9a20, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7fa51537b780, [], SA_RESTORER|SA_SIGINFO, 0x7fa515384130}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7fa51537b810, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7fa515384130}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
brk(0)                                  = 0x124c000
brk(0x126d000)                          = 0x126d000
brk(0)                                  = 0x126d000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=106065056, ...}) = 0
mmap(NULL, 106065056, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fa50ea8d000
close(3)                                = 0
setpgid(0, 0)                           = 0
rt_sigaction(SIGALRM, {0x402730, [], SA_RESTORER|SA_RESTART, 0x7fa515384130}, NULL, 8) = 0
rt_sigaction(SIGINT, {0x402730, [], SA_RESTORER|SA_RESTART, 0x7fa515384130}, NULL, 8) = 0
rt_sigaction(SIGQUIT, {0x402730, [], SA_RESTORER|SA_RESTART, 0x7fa515384130}, NULL, 8) = 0
rt_sigaction(SIGHUP, {0x402730, [], SA_RESTORER|SA_RESTART, 0x7fa515384130}, NULL, 8) = 0
rt_sigaction(SIGTERM, {0x402730, [], SA_RESTORER|SA_RESTART, 0x7fa515384130}, NULL, 8) = 0
rt_sigaction(SIGTERM, {0x402730, [], SA_RESTORER|SA_RESTART, 0x7fa515384130}, NULL, 8) = 0
rt_sigaction(SIGTTIN, {SIG_IGN, [TTIN], SA_RESTORER|SA_RESTART, 0x7fa514fe9650}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTTOU, {SIG_IGN, [TTOU], SA_RESTORER|SA_RESTART, 0x7fa514fe9650}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGCHLD, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7fa514fe9650}, {SIG_DFL, [], 0}, 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fa5159a9a10) = 20809
rt_sigprocmask(SIG_UNBLOCK, [ALRM], NULL, 8) = 0
timer_create(CLOCK_REALTIME, {0x124d030, SIGALRM, SIGEV_SIGNAL, {...}}, {0}) = 0
timer_settime(0, 0, {it_interval={0, 0}, it_value={20, 0}}, NULL) = 0
wait4(20809, 0x7fffc50c590c, 0, NULL)   = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_STOPPED, si_pid=20809, si_status=SIGTTOU, si_utime=0, si_stime=0} ---
--- SIGTTOU {si_signo=SIGTTOU, si_code=SI_KERNEL, si_value={int=22, ptr=0x7fc600000016}} ---

** HANGS HERE ***

wait4(20809, 0x7fffc50c590c, 0, NULL)   = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_TIMER, si_pid=0, si_uid=0, si_value=19189808} ---
kill(20809, SIGTERM)                    = 0
rt_sigaction(SIGTERM, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x7fa514fe9650}, {0x402730, [], SA_RESTORER|SA_RESTART, 0x7fa515384130}, 8) = 0
kill(0, SIGTERM)                        = 0
--- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=20808, si_uid=0} ---
kill(20809, SIGCONT)                    = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_CONTINUED, si_pid=20809, si_status=SIGCONT, si_utime=0, si_stime=0} ---
rt_sigaction(SIGCONT, {SIG_IGN, [CONT], SA_RESTORER|SA_RESTART, 0x7fa514fe9650}, {SIG_DFL, [], 0}, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=20809, si_status=SIGTERM, si_utime=0, si_stime=0} ---
kill(0, SIGCONT)                        = 0
--- SIGCONT {si_signo=SIGCONT, si_code=SI_USER, si_pid=20808, si_uid=0} ---
rt_sigreturn()                          = 61
wait4(20809, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGTERM}], 0, NULL) = 20809
close(1)                                = 0
close(2)                                = 0
exit_group(124)                         = ?
+++ exited with 124 +++
```

We can see that the child has stopped with SIGTTOU. This is because the default behaviour of the timeout command is to run children in the background when not running directly from a terminal:

```
       --foreground

              when not running timeout directly from a shell prompt,
              allow COMMAND to read from the TTY and get TTY signals; in this
              mode, children of COMMAND will not be timed out
```

Re-running with `--foreground` produces the desired behaviour:

```
# strace timeout --foreground 20s hpasmcli -s 'show asr'
execve("/usr/bin/timeout", ["timeout", "--foreground", "20s", "hpasmcli", "-s", "show asr"], [/* 25 vars */]) = 0
brk(0)                                  = 0x1592000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f53c092b000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=45950, ...}) = 0
mmap(NULL, 45950, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f53c091f000
close(3)                                = 0
open("/lib64/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\"\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=44088, ...}) = 0
mmap(NULL, 2128952, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f53c0503000
mprotect(0x7f53c050a000, 2093056, PROT_NONE) = 0
mmap(0x7f53c0709000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6000) = 0x7f53c0709000
close(3)                                = 0
open("/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240l\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=141616, ...}) = 0
mmap(NULL, 2208864, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f53c02e7000
mprotect(0x7f53c02fd000, 2097152, PROT_NONE) = 0
mmap(0x7f53c04fd000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x16000) = 0x7f53c04fd000
mmap(0x7f53c04ff000, 13408, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f53c04ff000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\34\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=2107760, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f53c091e000
mmap(NULL, 3932736, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f53bff26000
mprotect(0x7f53c00dc000, 2097152, PROT_NONE) = 0
mmap(0x7f53c02dc000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1b6000) = 0x7f53c02dc000
mmap(0x7f53c02e2000, 16960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f53c02e2000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f53c091d000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f53c091b000
arch_prctl(ARCH_SET_FS, 0x7f53c091b740) = 0
mprotect(0x7f53c02dc000, 16384, PROT_READ) = 0
mprotect(0x7f53c04fd000, 4096, PROT_READ) = 0
mprotect(0x7f53c0709000, 4096, PROT_READ) = 0
mprotect(0x60b000, 4096, PROT_READ)     = 0
mprotect(0x7f53c092c000, 4096, PROT_READ) = 0
munmap(0x7f53c091f000, 45950)           = 0
set_tid_address(0x7f53c091ba10)         = 20918
set_robust_list(0x7f53c091ba20, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7f53c02ed780, [], SA_RESTORER|SA_SIGINFO, 0x7f53c02f6130}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f53c02ed810, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f53c02f6130}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
brk(0)                                  = 0x1592000
brk(0x15b3000)                          = 0x15b3000
brk(0)                                  = 0x15b3000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=106065056, ...}) = 0
mmap(NULL, 106065056, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f53b99ff000
close(3)                                = 0
rt_sigaction(SIGALRM, {0x402730, [], SA_RESTORER|SA_RESTART, 0x7f53c02f6130}, NULL, 8) = 0
rt_sigaction(SIGINT, {0x402730, [], SA_RESTORER|SA_RESTART, 0x7f53c02f6130}, NULL, 8) = 0
rt_sigaction(SIGQUIT, {0x402730, [], SA_RESTORER|SA_RESTART, 0x7f53c02f6130}, NULL, 8) = 0
rt_sigaction(SIGHUP, {0x402730, [], SA_RESTORER|SA_RESTART, 0x7f53c02f6130}, NULL, 8) = 0
rt_sigaction(SIGTERM, {0x402730, [], SA_RESTORER|SA_RESTART, 0x7f53c02f6130}, NULL, 8) = 0
rt_sigaction(SIGTERM, {0x402730, [], SA_RESTORER|SA_RESTART, 0x7f53c02f6130}, NULL, 8) = 0
rt_sigaction(SIGTTIN, {SIG_IGN, [TTIN], SA_RESTORER|SA_RESTART, 0x7f53bff5b650}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTTOU, {SIG_IGN, [TTOU], SA_RESTORER|SA_RESTART, 0x7f53bff5b650}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGCHLD, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7f53bff5b650}, {SIG_DFL, [], 0}, 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f53c091ba10) = 20919
rt_sigprocmask(SIG_UNBLOCK, [ALRM], NULL, 8) = 0
timer_create(CLOCK_REALTIME, {0x1593030, SIGALRM, SIGEV_SIGNAL, {...}}, {0}) = 0
timer_settime(0, 0, {it_interval={0, 0}, it_value={20, 0}}, NULL) = 0
wait4(20919, 
ASR timeout is 10 minutes.
ASR is currently enabled.

[{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 20919
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=20919, si_status=0, si_utime=0, si_stime=0} ---
close(1)                                = 0
close(2)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by bmr-cymru** [comment] 2015-10-16 15:13
I have patch (against sos-3.2-15.el7) that introduces a new `fore` parameter to the command collection call sequence:

```diff
diff -up ./plugins/hpasm.py.orig ./plugins/hpasm.py
--- ./plugins/hpasm.py.orig	2015-10-16 15:58:12.514469677 +0100
+++ ./plugins/hpasm.py	2015-10-16 15:58:30.851559328 +0100
@@ -30,6 +30,6 @@ class Hpasm(Plugin, RedHatPlugin, Debian
         self.add_cmd_output([
             "hpasmcli -s 'show asr'",
             "hpasmcli -s 'show server'"
-        ], timeout=0)
+        ], fore=True)
 
 # vim: et ts=4 sw=4
diff -up ./plugins/__init__.py.orig ./plugins/__init__.py
--- ./plugins/__init__.py.orig	2015-10-16 15:16:03.966042853 +0100
+++ ./plugins/__init__.py	2015-10-16 16:01:38.598477527 +0100
@@ -460,8 +460,9 @@ class Plugin(object):
             self.copy_paths.update(copy_paths)
             self._log_info("added copyspec '%s'" % copyspec)
 
-    def get_command_output(self, prog, timeout=300, runat=None):
-        result = sos_get_command_output(prog, timeout=timeout, runat=runat)
+    def get_command_output(self, prog, timeout=300, runat=None, fore=False):
+        result = sos_get_command_output(prog, timeout=timeout, runat=runat,
+                                        fore=fore)
         if result['status'] == 124:
             self._log_warn("command '%s' timed out after %ds"
                            % (prog, timeout))
@@ -470,11 +471,12 @@ class Plugin(object):
             self._log_debug("could not run '%s': command not found" % prog)
         return result
 
-    def call_ext_prog(self, prog, timeout=300, runat=None):
+    def call_ext_prog(self, prog, timeout=300, runat=None, fore=False):
         """Execute a command independantly of the output gathering part of
         sosreport.
         """
-        return self.get_command_output(prog, timeout=timeout, runat=runat)
+        return self.get_command_output(prog, timeout=timeout, runat=runat,
+                                       fore=fore)
 
     def check_ext_prog(self, prog):
         """Execute a command independently of the output gathering part of
@@ -483,16 +485,16 @@ class Plugin(object):
         """
         return self.call_ext_prog(prog)['status'] == 0
 
-    def add_cmd_output(self, cmds, suggest_filename=None,
-                       root_symlink=None, timeout=300, runat=None):
+    def add_cmd_output(self, cmds, suggest_filename=None, root_symlink=None,
+                        timeout=300, runat=None, fore=False):
         """Run a program or a list of programs and collect the output"""
         if isinstance(cmds, six.string_types):
             cmds = [cmds]
         if len(cmds) > 1 and (suggest_filename or root_symlink):
             self._log_warn("ambiguous filename or symlink for command list")
         for cmd in cmds:
-            cmdt = (cmd, suggest_filename, root_symlink, timeout, runat)
-            _logstr = "packed command tuple: ('%s', '%s', '%s', %s, '%s')"
+            cmdt = (cmd, suggest_filename, root_symlink, timeout, runat, fore)
+            _logstr = "packed command tuple: ('%s', '%s', '%s', %s, '%s', %s)"
             self._log_debug(_logstr % cmdt)
             self.collect_cmds.append(cmdt)
             self._log_info("added cmd output '%s'" % cmd)
@@ -547,12 +549,14 @@ class Plugin(object):
 
     def get_cmd_output_now(self, exe, suggest_filename=None,
                            root_symlink=False, timeout=300,
-                           runat=None):
+                           runat=None, fore=False):
         """Execute a command and save the output to a file for inclusion in the
         report.
         """
         start = time()
-        result = self.get_command_output(exe, timeout=timeout, runat=runat)
+        result = self.get_command_output(exe, timeout=timeout, runat=runat,
+                                         fore=fore)
+
         # 126 means 'found but not executable'
         if result['status'] == 126 or result['status'] == 127:
             return None
@@ -601,13 +605,16 @@ class Plugin(object):
 
     def _collect_cmd_output(self):
         for progs in zip(self.collect_cmds):
-            prog, suggest_filename, root_symlink, timeout, runat = progs[0]
+            (
+                prog, suggest_filename, root_symlink,
+                timeout, runat, fore
+            ) = progs[0]
             self._log_debug("unpacked command tuple: "
-                            + "('%s', '%s', '%s', %s, '%s')" % progs[0])
+                            + "('%s', '%s', '%s', %s, '%s', %s)" % progs[0])
             self._log_info("collecting output of '%s'" % prog)
             self.get_cmd_output_now(prog, suggest_filename=suggest_filename,
                                     root_symlink=root_symlink,
-                                    timeout=timeout, runat=runat)
+                                    timeout=timeout, runat=runat, fore=fore)
 
     def _collect_strings(self):
         for string, file_name in self.copy_strings:
diff -up ./utilities.py.orig ./utilities.py
--- ./utilities.py.orig	2015-10-16 15:23:26.528220795 +0100
+++ ./utilities.py	2015-10-16 15:25:41.205883651 +0100
@@ -121,7 +121,7 @@ def is_executable(command):
     return any(os.access(path, os.X_OK) for path in candidates)
 
 
-def sos_get_command_output(command, timeout=300, runat=None):
+def sos_get_command_output(command, timeout=300, runat=None, fore=False):
     """Execute a command through the system shell. First checks to see if the
     requested command is executable. Returns (returncode, stdout, 0)"""
     def _child_chdir():
@@ -136,7 +136,8 @@ def sos_get_command_output(command, time
     cmd_env['LC_ALL'] = 'C'
     # use /usr/bin/timeout to implement a timeout
     if timeout and is_executable("timeout"):
-        command = "timeout %ds %s" % (timeout, command)
+	fg_arg = "--foreground" if fore else ""
+        command = "timeout %s %ds %s" % (fg_arg, timeout, command)
 
     # shlex.split() reacts badly to unicode on older python runtimes.
     if not six.PY3:
```

It needs porting to current master since the version of sos it is based on does not include the container changes (which touch the same family of functions).

Overall I am not thrilled at adding yet-more-crap to this interface to support one particular use but this appears to be the best current compromise between losing all timeout protection for these commands versus taking 5m timeouts on systems where hpasm is in use.

It would be ideal if we could automate this somehow but there does not appear to be any reasonable way to tell externally whether a binary will interact with the terminal in this way and I am reluctant to introduce a blacklist into the lower levels of the interface (i.e. `sos_get_command_output`) to deal with what is hopefully a fairly rare requirement.

Thoughts?

**Comment by battlemidget** [comment] 2015-10-16 15:20
Yea i don't see another way to deal with this behavior without inspecting the command options beforehand. Though couldn't we just call `--foreground` on the specific command that requires it, like directly in the plugin itself?

**Comment by bmr-cymru** [comment] 2015-10-16 15:32
Only if the plugin also calls 'timeout' by itself - which kinda weakens the whole "get command with configurable timeout" API thing.

We either need a way to figure out if it's needed (possibly via blacklist), or we need to propagate a `foreground` boolean all the way up to plugins.

It *might* work given current string munging strategies to do something like:

```python
    self.add_cmd_output("--foreground some_cmd_that_hangs_on_tty")
```

But that's so evil & gross I can't even contemplate doing it :-D

**Comment by bmr-cymru** [comment] 2015-10-16 15:32
I am actually starting to talk myself into this whole blacklist thing...

**Comment by bmr-cymru** [comment] 2017-09-04 10:29
Corresponding PR was merged months ago: closing.

**Closed by bmr-cymru** 2017-09-04 10:29 UTC
