### ISSUE TITLE
Log collection error: AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by KellenRenshaw** [sosreport/sos#1421] opened 2018-09-08 00:04 UTC
Platform: Ubuntu 14.04
Sosreport version: 3.5-1~ubuntu14.04.2

Issue:
logs and upstart plugin error out and fail to collect complete logs.

Sample error (identical for both logs and upstart):
Traceback (most recent call last):
  File "/usr/share/sosreport/sos/sosreport.py", line 1300, in collect
    plug.collect()
  File "/usr/share/sosreport/sos/plugins/__init__.py", line 877, in collect
    self._collect_strings()
  File "/usr/share/sosreport/sos/plugins/__init__.py", line 860, in _collect_strings
    (content.splitlines()[0]).decode('utf8', 'ignore'))
AttributeError: 'str' object has no attribute 'decode'

**Comment by pmoravec** [comment] 2018-09-08 07:53
This matches #1267 fixed by commit 476bd7f , and that fix *is* present in 3.5-1. And I can't reproduce it on Ubuntu 16 (I know you have older):

    mkdir 3.5-1
    cd 3.5-1
    wget https://github.com/sosreport/sos/archive/3.5.1.zip
    unzip 3.5.1.zip 
    cd sos-3.5.1/
    ./sosreport -o logs,upstart --batch
    ..
     Running plugins. Please wait ...

      Running 1/2: logs...        
      Running 2/2: upstart...        

    Creating compressed archive...

    Your sosreport has been generated and saved in:
    ..

Could you try the same, please? Or ideally, as this is upstream, could you verify against upstream? (replace URL in the `wget` by `https://github.com/sosreport/sos/archive/master.zip`)

**Comment by pmoravec** [comment] 2018-09-08 15:58
Coincidentally I hit similar (but not identical) problem on current upstream now - see #1422.

**Comment by TurboTurtle** [comment] 2020-04-02 15:06
Closing as a fixed issue per Pavel's comments above.

**Closed by TurboTurtle** 2020-04-02 15:06 UTC
