### ISSUE TITLE
Extend PR template questionnaire by PR reference check

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1792] opened 2019-09-20 07:29 UTC
Shall not we extend the PR template questionnaire (the "Please place an 'X' inside each '[]' to confirm you adhere to our Contributor Guidelines" text) by a check like

    [] Does the latest commit refer to an issue or PR it resolves?

On one side, one extra piece of work for comiters (another 'X' to type), on the other side see #1789 or #1790.

**Comment by TurboTurtle** [comment] 2019-09-20 19:27
My only question is, is there some git hook available that could automatically handle this? I know its possible with gerrit, but I've honestly not looked for git.

**Comment by iranzo** [comment] 2019-10-03 14:39
Github handles it when issuing the Closes #XXXX or Fixes #xxxx so that the issue is closed when merged.

Gerrit does something similar too and even with other software like OSP's Zuul, can do partial fixes, depends, etc

**Comment by bmr-cymru** [comment] 2019-10-03 14:44
We already ask people to use the tags ("Resolves" for a PR and "Closes" for an issue, ideally), but I don't think there's any adequate way to automatically check for this. It's far easier for a human reviewer to point out than to try to guess what something might be fixing from an automatic check.

**Comment by TurboTurtle** [comment] 2019-10-03 16:48
I'm not referring to the auto-closure itself, I'm talking about a hook that automatically amends the commit message to include the 'Closes:' line for the PR being opened.

The oVirt Gerrit does something similar - it [generates and appends a change ID](https://www.ovirt.org/develop/dev-process/working-with-gerrit.html#installing-the-change-id-hook) to the commit message.

Is there a way for us to automatically grab the # for the to-be-opened PR, and appends that to the commit message at PR creation time? Otherwise, we'll either have contributors force-pushing immediately after opening a new PR, or have times when there are incorrect references in the commit (e.g. since this would all be manual, a contributor could see the latest _open_ PR is AAAA, the latest issue is AAAB, assume they will get AAAC but instead get AAAD since AAAC is already used by a closed issue/PR).

**Comment by iranzo** [comment] 2019-10-03 17:14
In the case of gerrit, the change ID is static as it's used to refer to that change in particular, so that several commits must be 'ammended' to be just one commit with just one 'change-id', this allows gerrit to keep track of each revision for the same 'change', and the interface allows to see the different versions of it.

git-review takes care also of complaining if you're trying to submit more than one commit per 'review'

In other repos like kubevirt, that uses 'just github', they have a boot that automatically removes the /lgtm and the /approve once there are new changes, so a new review is required.

I don't see how do you want to correlate a new PR and an issue.

If you want to have always a change ID or even if you want 'prechecks' I would recommend looking at 'precommit' https://pre-commit.com/

It can even automate some formatting on files, or some initial checks before the original commit happens (like formatted subject, etc)

**Comment by bmr-cymru** [comment] 2019-10-03 17:42
> I'm not referring to the auto-closure itself, I'm talking about a hook that automatically amends the commit message to include the 'Closes:' line for the PR being opened.

I'm not a fan of any hook that modifies commits - it means that either the committer then has to immediately pull to pick up some new commit object that was auto-generated, or worse, if the commit is actually *amended*, reset back to some prior commit and re-pull.

> The oVirt Gerrit does something similar - it generates and appends a change ID to the commit message.

Well, I've always hated Gerrit, but maybe that's just me ;-)

**Comment by bmr-cymru** [comment] 2019-10-03 17:43
It also really breaks batch pushes, so unless there's some way to avoid that (I don't think there is) I think that's a strong nack from me.

**Comment by iranzo** [comment] 2019-10-04 08:05
The PR I made covers the described form changes by pmoravec (nothing modified other than that)

**Comment by TurboTurtle** [comment] 2020-01-28 20:52
Closing, as this is addressed via 5c3287a

**Closed by TurboTurtle** 2020-01-28 20:52 UTC
