### ISSUE TITLE
[juju] plugin restarts juju-db service

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1893] opened 2019-12-12 21:10 UTC
See `ensure_service_is_running` method that executes `service juju-db stop` followed by `service juju-db start` (https://github.com/sosreport/sos/blob/master/sos/plugins/juju.py#L16-L31). We aim sos report not intercepting the target system (cf. with `--allow-system-changes` option), what promise is broken here.

As I dont know the plugin or the service, I am asking @niedbalski and @battlemidget for a review.

**Comment by BryanQuigley** [comment] 2019-12-13 00:10
This is indeed a critical issue (I thought it was already fixed)- and it's actually patched out in our released sosreport IIRC.  

This is fixed in #1670, but I'm going to suggest we drop any difficult bits (runuser/sudo/etc) and just get something moving to fix these glaring issues.

**Comment by slashdd** [comment] 2019-12-18 18:17
@pmoravec I have temporarily fixed it in Ubuntu sosreport for now by removing the offending function and its call, waiting for the juju refactoring plugin(s) to be completed.

**Comment by BryanQuigley** [comment] 2020-01-28 22:08
Oh, this is a dupe of #1653

**Closed by BryanQuigley** 2020-01-28 22:08 UTC
Labels: high
