### ISSUE TITLE
--all-logs truncates files over log_size to 0 bytes, --log-size is not effective.

### ISSUE THREAD

**Issue by mjg123** [sosreport/sos#586] opened 2015-06-22 10:36 UTC
Sosreport:
```
# sosreport -version

sosreport (version 3.2.0a1)
```

A largeish log file:
```
# ls -l /var/log/auth.log
-rw-r----- 1 root adm 24550115 Jun 22 10:27 /var/log/auth.log
```

Create the report:
```
# sosreport --all-logs

sosreport (version 3.2.0a1)

This command will collect system configuration and diagnostic
information from this Debian system. An archive containing the collected
information will be generated in /tmp.

For more information on the Debian project visit:

  http://www.debian.org/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.

Press ENTER to continue, or CTRL-C to quit.

Please enter your first initial and last name [PADAWANBASE-CCP-CPN-N0001-NETCLM]: 
Please enter the case id that you are generating this report for: 

 Setting up archive ...
 Setting up plugins ...
 Running plugins. Please wait ...

  Running 1/62: acpid...        
  Running 2/62: apport...        
  Running 3/62: apt...        
  Running 4/62: autofs...        
  Running 5/62: block...        
  Running 6/62: boot...        
  Running 7/62: cgroups...        
  Running 8/62: cron...        
  Running 9/62: cups...        
  Running 10/62: dbus...        
  Running 11/62: devicemapper...        
  Running 12/62: dmraid...        
  Running 13/62: dpkg...        
  Running 14/62: ephemeral_pki...        
  Running 15/62: filesys...        
  Running 16/62: gdm...        
  Running 17/62: general...        
  Running 18/62: grub...        
  Running 19/62: grub2...        
  Running 20/62: hardware...        
  Running 21/62: helion...        
  Running 22/62: i18n...        
  Running 23/62: ipvs...        
  Running 24/62: java...        
  Running 25/62: kernel...        
  Running 26/62: krb5...        
  Running 27/62: kvm...        
  Running 28/62: ldap...        
  Running 29/62: libvirt...        
  Running 30/62: logrotate...        
  Running 31/62: logs...        
  Running 32/62: lsbrelease...        
  Running 33/62: lvm2...        
  Running 34/62: md...        
  Running 35/62: memory...        
  Running 36/62: multipath...        
  Running 37/62: named...        
  Running 38/62: networking...        
  Running 39/62: nscd...        
  Running 40/62: openssl...        
  Running 41/62: openvswitch...        
  Running 42/62: pam...        
  Running 43/62: pci...        
  Running 44/62: postfix...        
  Running 45/62: ppp...        
  Running 46/62: procenv...        
  Running 47/62: process...        
  Running 48/62: processor...        
  Running 49/62: python...        
  Running 50/62: scsi...        
  Running 51/62: snmp...        
  Running 52/62: soundcard...        
  Running 53/62: ssh...        
  Running 54/62: sssd...        
  Running 55/62: startup...        
  Running 56/62: system...        
  Running 57/62: systemtap...        
  Running 58/62: sysvipc...        
  Running 59/62: udev...        
  Running 60/62: upstart...        
  Running 61/62: usb...        
  Running 62/62: xfs...        

Creating compressed archive...

Your sosreport has been generated and saved in:
  /tmp/sosreport-PADAWANBASE-CCP-CPN-N0001-NETCLM-20150622102737.tar.xz

The checksum is: 60de93208c1dee603b67135d8306c4bd

Please send this file to your support representative.
```

Untar the report:
```
# tar xvf /tmp/sosreport-PADAWANBASE-CCP-CPN-N0001-NETCLM-20150622102737.tar.xz 
...snip...
sosreport-PADAWANBASE-CCP-CPN-N0001-NETCLM-20150622102737/var/log/auth.log
...snip...
```

Is the log file there?
```
# ls -l sosreport-PADAWANBASE-CCP-CPN-N0001-NETCLM-20150622102737/var/log/auth.log
lrwxrwxrwx 1 root root 46 Jun 22 10:27 sosreport-PADAWANBASE-CCP-CPN-N0001-NETCLM-20150622102737/var/log/auth.log -> ../../sos_strings/logs/var.log.auth.log.tailed
```

Follow the symlink:
```
# ls -l sosreport-PADAWANBASE-CCP-CPN-N0001-NETCLM-20150622102737/sos_strings/logs/var.log.auth.log.tailed 
-rw-r--r-- 1 root root 0 Jun 22 10:27 sosreport-PADAWANBASE-CCP-CPN-N0001-NETCLM-20150622102737/sos_strings/logs/var.log.auth.log.tailed
```

It's 0-bytes. So, in effect, the whole file is missing from the report.  The obvious workaround of setting `--log-size=${some_large_value}` does not work - it looks like it's being ignored.

**Comment by bmr-cymru** [comment] 2015-06-22 10:45
> # sosreport -version
> 
> sosreport (version 3.2.0a1)

Thanks for the report. The 3.2-alpha1 release is pretty ancient now (over 12 months) - I'll try to reproduce this on current master but you might want either update locally or file a bug report with your distribution to update to a later final release version (3.2 final was released last September and is packaged by most major distros now).

**Comment by mjg123** [comment] 2015-06-22 12:06
Thank you as well - my distro is based on Debian Jessie and seems to be up to date with their repos (https://packages.debian.org/jessie/sosreport):

```
# apt-cache policy sosreport
sosreport:
  Installed: 3.2-2
  Candidate: 3.2-2
  Version table:
 *** 3.2-2 0
        500 http://repo02.gozer.hpcloud.net/apt/hlinux-deejay.usa.hp.com//hLinuxArchive/2015/repo.2015-05-13/ cattleprod/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by mjg123** [comment] 2015-06-22 12:17
One more datapoint, which has confused me a little. Cloning the latest from github, master branch, the issue does not happen (ie the linked file is 10mb which I assume is the default). The version is still reported the same though:

```
# ./sosreport -version

sosreport (version 3.2.0a1)
```

**Comment by bmr-cymru** [comment] 2015-06-22 13:07
A version of `3.2-2` is much later - `3.2.0a1` is the first alpha release preceding 3.2. I would expect `3.2-2` to package the final 3.2 release plus possibly later patches.

Distros differ in naming and numbering conventions for pre-release packages but usually the "alpha tag" is added either in the version or release field.

> \# ./sosreport -version
>
> sosreport (version 3.2.0a1)

Looks like the `__version__` string in the sos package's `__init__.py` never got updated - sorry about that. I'll push a fix to master today.

**Comment by mjg123** [comment] 2015-06-22 13:23
Yep - looks like we actually have `3.2` installed, reporting itself incorrectly as `3.2.0a1`. But, like I said, the issue does not occur with the `3.2` tag checked out from source repo. So I need to look more closely to see where the problem is coming from. Thanks for your help so far.

**Comment by mjg123** [comment] 2015-06-22 14:36
So our (locally sourced, free range) package uses `python3` here https://github.com/sosreport/sos/blob/master/sosreport#L1 - changing this back to `python` fixes the problem. So I'll leave this for you to close or perhaps treat as a py3-only bug.

**Comment by bmr-cymru** [comment] 2015-06-22 14:42
Thanks - that's useful information. I'll check a python3 build from master and see if I can reproduce this.

**Comment by BryanQuigley** [comment] 2015-07-09 16:56
I think I've also ran into this with 593.   Also I can reproduce with logs.py if both syslog and syslog.1 are present and bigger than size limit.

Code is:
            self.add_copy_spec_limit("/var/log/syslog", sizelimit=limit)
            self.add_copy_spec_limit("/var/log/syslog.1", sizelimit=limit)

And output is (sos_strings/logs/):
 -rw-r--r-- 1 root root       0 Jul  9 12:50 var.log.syslog.1.tailed
-rw-r--r-- 1 root root 5242880 Jul  9 12:50 var.log.syslog.tailed

That should have them both stop at sizelimit right?

**Comment by bmr-cymru** [comment] 2015-07-10 10:38
What was `limit` at this time?

**Comment by BryanQuigley** [comment] 2015-07-10 12:49
--size-limit=5

**Comment by bmr-cymru** [comment] 2015-07-10 13:29
Then it's doing the right thing wrt limiting; 5 * 1024 * 1024 == 5242880. It's just creating an unnecessary 0-byte file for a file that should be skipped entirely.

**Comment by bmr-cymru** [comment] 2015-07-11 17:41
> That should have them both stop at sizelimit right?

No - the limit is applied per call to `add_copy_spec_limit()` not per file.

**Comment by BryanQuigley** [comment] 2015-07-16 13:54
I have two separate add_copy_spec_limit() calls in the above example.   Is it really per plugin or something?

**Comment by bmr-cymru** [comment] 2015-07-16 15:05
There's no persistence of the `sizelimit` value between calls:

```python
    def add_copy_spec_limit(self, copyspec, sizelimit=None, tailit=True):
        """Add a file or glob but limit it to sizelimit megabytes. If fname is
        a single file the file will be tailed to meet sizelimit. If the first
        file in a glob is too large it will be tailed to meet the sizelimit.
        """
        if not (copyspec and len(copyspec)):
            return False

        if self.use_sysroot():
            copyspec = self.join_sysroot(copyspec)
        files = glob.glob(copyspec)
        files.sort()
        if len(files) == 0:
            return

        current_size = 0
        limit_reached = False
        sizelimit *= 1024 * 1024  # in MB
        _file = None

        for _file in files:
            current_size += os.stat(_file)[stat.ST_SIZE]
            if sizelimit and current_size > sizelimit:
                limit_reached = True
                break
            self._add_copy_paths([_file])

        if limit_reached and tailit:
            file_name = _file

            if file_name[0] == os.sep:
                file_name = file_name.lstrip(os.sep)
            strfile = file_name.replace(os.path.sep, ".") + ".tailed"
            self.add_string_as_file(tail(_file, sizelimit), strfile)
            rel_path = os.path.relpath('/', os.path.dirname(_file))
            link_path = os.path.join(rel_path, 'sos_strings',
                                     self.name(), strfile)
            self.archive.add_link(link_path, _file)

```

**Comment by BryanQuigley** [comment] 2015-07-16 15:07
> It's just creating an unnecessary 0-byte file for a file that should be skipped entirely.
So it should have captured both files at that limit instead?

**Comment by bmr-cymru** [comment] 2015-07-16 15:08
> So it should have captured both files at that limit instead?

If you are making two calls then yes.

**Comment by bmr-cymru** [comment] 2015-07-16 15:09
I would sprinkle some `_log_debug()` calls into `add_copy_spec_limit()` - if you want to do that "properly" I'd be happy to merge something that makes debugging it easier. Otherwise just do a few "got here" and "limit is:" type prints to understand what's going on in your case.

**Comment by karibou** [comment] 2015-07-20 08:45
For the sake of completeness, the following bug has been opened on Debian to track the issue by another user experiencing the same problem : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792732

**Comment by karibou** [comment] 2015-07-20 12:13
ok, I think I have identified the root cause in sos/archive.py : 

def add_string(self, content, dest):                                         
        src = dest                                                               
        dest = self.dest_path(dest)                                              
        self._check_path(dest)                                                   
        f = codecs.open(dest, 'w', encoding='utf-8')                             
        f.write(content)

The content variable is a string in py2 not in py3 so f.write() fails. I'm working on a fix atm

**Comment by bmr-cymru** [comment] 2015-07-20 12:20
Why would the first call work then?

**Comment by bmr-cymru** [comment] 2015-07-20 12:20
Are you saying the encoding is different in the rotated files?

**Comment by karibou** [comment] 2015-07-20 12:21
dunno, I'm not testing with Bryan's change, just a standard setup

**Comment by bmr-cymru** [comment] 2015-07-20 12:22
Well both the .tailed files are stored in the archives as strings so both must have passed through the above code - I'm not saying this isn't the cause but I am suspicious because the non-rotated file is written just fine.

**Comment by karibou** [comment] 2015-07-20 13:34
I just tested on trunk. When using : 
 # sosreport --batch -o logs

I get the behavior reported in the bug, even with the syslog & syslog.1 files

 When using : 
 # sosreport --batch -o logs --all-logs

Both syslog & syslog.1 do not get picked up accorging to : 

    def setup(self):
        super(DebianLogs, self).setup()
        if not self.get_option("all_logs"): <<<<<<<<<<<<<<<<<
            limit = self.get_option("log_size")

Running with py2 gives the expected result : tailed files are populated if --all-logs is not used

**Comment by bmr-cymru** [comment] 2015-07-20 14:01
Fedora is just in the process of moving to a native py3 build so I can try testing with that. It's probably going to be a week or so before I have time however.

What I'd suggest if you think this has to do with exceptions in archive code is to just hack out the exception handling around the call you think is failing (i.e. `collect()` at highest level).

I'm assuming there's nothing useful when you reproduce with `-vvv --debug`?

**Comment by karibou** [comment] 2015-07-20 14:30
well, I think I have a fix for it. I'm also working on a specific test for that, as well as a minor tweak to add python3 test coverage

**Comment by karibou** [comment] 2015-07-21 08:14
add_copy_spec_limit does a tail() to limit the size of the file : 

def tail(filename, number_of_bytes):
    """Returns the last number_of_bytes of filename"""
    with open(filename, "rb") as f:
        if os.stat(filename).st_size > number_of_bytes:
            f.seek(-number_of_bytes, 2)
        return f.read()

open(filename, "rb") and then return f.read() will return a string in python2 and a unicode in python3. It laters make add_string() fail since this one expects a string.

**Comment by battlemidget** [comment] 2015-09-29 15:50
Are we able to get a standalone test script that shows this behavior?

**Closed** 2015-10-15 11:04 UTC
