### ISSUE TITLE
I get an error on every run due to #1456

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#1594] opened 2019-03-19 17:11 UTC
$sudo python3 sosreport
....
Please send this file to your support representative.

Traceback (most recent call last):
  File "sosreport", line 19, in <module>
    main(sys.argv[1:])
  File "/home/bryan/git/sos/sos/sosreport.py", line 1504, in main
    sos._cleanup()
  File "/home/bryan/git/sos/sos/sosreport.py", line 1444, in _cleanup
    rmtree(self.tmpdir)
  File "/usr/lib/python3.7/shutil.py", line 482, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.7/shutil.py", line 480, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/sos.uug9bl0t'

.. and the error is reported in Travis but still returns 0 so it doesn't get flagged..

**Comment by BryanQuigley** [comment] 2019-03-19 17:12
@TurboTurtle 
I get this error every time now due to https://github.com/sosreport/sos/commit/96e83e3b0ce09ee89641d0b34b05c1eadaca599b

**Comment by bmr-cymru** [comment] 2019-03-19 17:16
Don't worry, we'll get this sorted for 3.7. We're trying to get through the merge backlog this week, so expect some bumps in master while we get it all settled down again.

**Comment by bmr-cymru** [comment] 2019-03-19 17:25
OK, here's what's going on: during a normal exit, we raise `SystemExit`, which takes us through the cleanup handlers and tidies up `/tmp`.

The commit was intended to plug a gap for `sosreport -l` - the problem is that that just falls off the end of main, it doesn't raise an exception or take the usual cleanup paths, so with this patch, `sosreport` is correct for the `-l` case, and broken for everything else.

I'm in the middle of merging a bunch of PRs at the minute, and I'll take a look at this when I'm done, but there are a couple obvious solutions:

 * Raise `SystemExit` out of the `-l` path
 * Make `_cleanup()` conditional on `args.list` in `main()`

I'm more in favour of the first for now - it makes all the paths through `sosreport` consistent and makes it less likely we'll add more warts like this in the future. I don't think there's any reason it wouldn't work so I'll try that first.

(I hadn't run into this in my merge testing, because I drop individual plugins into `/usr/lib/...` for testing, and run with the system-provided sos libraries and binary).

**Comment by BryanQuigley** [comment] 2019-03-19 17:30
Gotcha, thanks for the quick analysis.  I'm not worried :), no rush now that I know it doesn't impact anything else I can still do other changes.

**Comment by bmr-cymru** [comment] 2019-03-19 17:34
Should be fixed - let me know if you see any other problems!

**Closed** 2019-03-19 17:33 UTC
