### ISSUE TITLE
[navicli] plugin requires input even in --batch mode

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#970] opened 2017-03-24 21:31 UTC
Code:

            CLARiiON_IP_loop = "stay_in"
            while CLARiiON_IP_loop == "stay_in":
                try:
                    ans = input("CLARiiON SP IP Address or [Enter] to exit: ")
                except:
                    return

in `navcli` plugin requires human input even when `sosreport` is invoked with `--batch` option. The plugin setup should take empty string instead (in this situation).

**Comment by bmr-cymru** [comment] 2017-05-31 11:26
Duplicate of #405.

**Closed by bmr-cymru** 2017-05-31 11:26 UTC
