### ISSUE TITLE
caught exception in plugin method "logs.collect()"

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#1301] opened 2018-05-18 14:55 UTC
- Problem

sosreport logs plugin fails as follow
 ```
 Running 22/51: logs...        
caught exception in plugin method "logs.collect()"
writing traceback to sos_logs/logs-plugin-errors.txt
  Running 23/51: lsbrelease...   
```
when logfiles in /var/log are too large.

- Reproducer

I was able to reproduce by exaggerating kern.log size to 1Gb and then run sosreport upstream (version 3.5)
`sudo python3 ./sosreport -a --config ./sos.conf
`
- Note:

It doesn't caught exception if "--all-logs" option is in use.

```
--all-logs
              Tell plugins to collect all possible log data ignoring any size limits and including logs in non- 
              default locations. This option may significantly increase the size of reports.
```

- Logs

/tmp/sosreport_dir/sos_logs/logs-plugin-errors.txt
```
Traceback (most recent call last):
  File "/var/tmp/sos/sos/sosreport.py", line 1300, in collect
    plug.collect()
  File "/var/tmp/sos/sos/plugins/__init__.py", line 877, in collect
    self._collect_strings()
  File "/var/tmp/sos/sos/plugins/__init__.py", line 860, in _collect_strings
    (content.splitlines()[0]).decode('utf8', 'ignore'))
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by slashdd** [comment] 2018-05-18 14:56
This situation has been first brought to my attention in https://bugs.launchpad.net/bugs/1767943

**Comment by bmr-cymru** [comment] 2018-05-18 15:07
Looks like a duplicate of #1267 - fix is in the review queue, should land next week with any luck.

We're planning to make a 3.5.1 interim release shortly to help distro packagers who cannot wait until 3.6 final is out - this fix will be included in that tag.

**Comment by slashdd** [comment] 2018-05-18 15:08
Thanks bmr-cymru

**Comment by bmr-cymru** [comment] 2018-05-18 15:08
There's a patch in the pull that should fix this for both Py2 and Py3 if you wanted to apply it locally or test it out.

**Comment by urvashijawere** [comment] 2018-06-13 10:58
``From: Urvashi Jawere <urjawere@in.ibm.com>
Date: Mon, 30 Apr 2018 11:16:33 +0530
Subject: [PATCH] Changes to support Python new versions in sosreport utility.

--- __init__.py.old	2018-04-27 07:40:16.023921584 -0400
+++ __init__.py	2018-04-27 07:10:12.253482038 -0400
@@ -857,7 +857,7 @@ class Plugin(object):
                 content = "..." + content.splitlines()[0]
             else:
                 content = ("..." +
-                           (content.splitlines()[0]).decode('utf8', 'ignore'))
+                           (content.splitlines()[0]))
             self._log_info("collecting string '%s' as '%s'"
                            % (content, file_name))
             try:
``

**Comment by urvashijawere** [comment] 2018-06-13 10:59
Above patch resolved the issue..

**Comment by bmr-cymru** [comment] 2018-06-13 13:04
Above patch is a duplicate of the fix we merged three weeks ago ;-)

**Closed by bmr-cymru** 2018-06-13 13:04 UTC
