### ISSUE TITLE
[sosreport] make JSON report

### ISSUE THREAD

**Issue by Amitgb14** [sosreport/sos#793] opened 2016-03-30 05:57 UTC
Currently sosreport generate plaintext and html format report, my suggestion to make report in JSON format will be better useful in future.

**Comment by bmr-cymru** [comment] 2016-03-30 09:51
Duplicate of #90 - there's a whole lot of context for the issue and its background there.

I don't see why we would want to start all that discussion again?

**Closed by bmr-cymru** 2016-03-30 09:51 UTC
