### ISSUE TITLE
[openvswitch] plugin fails to collect information sometimes

### ISSUE THREAD

**Issue by codificat** [sosreport/sos#782] opened 2016-03-03 12:20 UTC
In an OpenShift environment:

```
# cat sos_commands/openvswitch/ovs-ofctl_dump-flows_br0
2016-03-01T21:00:15Z|00001|vconn|WARN|unix:/var/run/openvswitch/br0.mgmt: version negotiation failed (we support version 0x01, peer supports version 0x04)
ovs-ofctl: br0: failed to connect to socket (Broken pipe)
```

Specifying `-O OpenFlow13` works, but modifying the plugin to specify the version doesn't sound right. Well, maybe adding an extra line with the version explicitly might be an acceptable hack, but is there a better way?

**Comment by bmr-cymru** [comment] 2016-03-03 12:41
First question is why is it happening?

I am assuming this is similar to the problems we've had with NetworkManager protocol version checks - the copy in the file system has been updated but the running daemon still uses the old version?

(although in the output above it seems like the client has the newer version?)

There are some valid reasons for these services not restarting themselves (e.g. in NM's case it would kill all running VPN sessions etc.) but this is somewhat painful for us to deal with in sos.

Let's confirm the cause in this instance and then we can try to work out a strategy for handling it.

**Comment by codificat** [comment] 2016-03-08 15:11
The man page for `ovs-ofctl(8)` in `openvswitch-2.4.0-1.el7` says:

> Because support for OpenFlow 1.1 and later is still experimental in Open vSwitch,
> it is necessary to explicitly enable these protocol  versions  in  ovs-ofctl
> (using -O) and in the switch itself (with the protocols column in the Bridge table).
> For more information, see ``Q: What versions of OpenFlow does Open vSwitch support?'' in the Open vSwitch FAQ.

This seems to be [the FAQ in question](https://github.com/openvswitch/ovs/blob/master/FAQ.md#q-what-versions-of-openflow-does-open-vswitch-support), and the info there doesn't seem to match the man page above, as it suggests that OF1.3 is enabled by default starting in ovs 2.3.

So, there's some conflicting documentation here, would have to dig the sources/package to determine exact details.

Listing all protocols explicitly in `-O` should avoid relying on the (apparently fragile) auto-negotiation. Should we? (at the risk of specifying protocol versions not supported by the installed ovs...)

**Comment by pmoravec** [comment] 2016-05-07 15:06
"Listing all protocols explicitly in -O" - will the negotiation choose some of the supported version? I.e. specifying `-O X,Y` and ovs supporting just Y, will the protocol version Y be chosen?

If so, the workaround is meaningfull (until ovs abandons currently used protocol versions in favour of some new ones).

**Comment by bmr-cymru** [comment] 2017-06-22 14:09
Should be fixed by the multi-protocol version changes in pull #1040

**Closed by bmr-cymru** 2017-06-22 14:09 UTC
