### ISSUE TITLE
[containers] Grab rpm data from containers

### ISSUE THREAD

**Issue by iranzo** [sosreport/sos#1164] opened 2017-12-12 12:10 UTC
Currently we've data from container used image by docker inspect but it might happen that the image has been modified and even if it's named and just the sha differs, it can contain a hotfix, etc.

it would be good to grab in the docker sos_commands folder the rpm -qa output for each container as per, for example:

~~~
[root@controller-0 rpm]# rpm -qa —dbpath /var/lib/docker/overlay2/0d057df79bca42f6c95bc252e9e03f250c61e85ef94e4fbe4650d8eacf401a88/merged/var/lib/rpm|grep nova
openstack-nova-common-16.0.2-3.el7ost.noarch
python-novaclient-9.1.1-1.el7ost.noarch
python-nova-16.0.2-3.el7ost.noarch
openstack-nova-scheduler-16.0.2-3.el7ost.noarch
~~~

Ideally sosreport should iterate over each overlay2 folder and use it with rpm -qa --dbpath and store output so we can check real specific versions inside each container

**Comment by bmr-cymru** [comment] 2017-12-12 13:13
I am not presently convinced that this does not belong in some container utility.

**Comment by iranzo** [comment] 2017-12-12 13:15
~~~
[piranzo@collab-shell docker]$ pwd
/cases/01991880/sosreport-20171212-110525/controller-0/sos_commands/docker
[piranzo@collab-shell docker]$ ls
docker_images                docker_inspect_54a46e928b71  docker_inspect_c86032ca69f9
docker_info                  docker_inspect_557326bcc9dc  docker_inspect_cbca09c9281d
docker_inspect_013f7757edbd  docker_inspect_63401e85a617  docker_inspect_d0962acf4cea
docker_inspect_02a5d6b46743  docker_inspect_65a77745758d  docker_inspect_d7f795cc753a
docker_inspect_02e4e749dd90  docker_inspect_67666d5822d5  docker_inspect_e9a61565f62f
docker_inspect_05e8645a5177  docker_inspect_67fa5b66e8d2  docker_inspect_ea2fa5d505b2
docker_inspect_0a29520f2478  docker_inspect_6ecf315a7090  docker_inspect_f20afc28ece1
docker_inspect_0c194af0dce0  docker_inspect_7d1aec729e99  docker_inspect_f794750ddc59
docker_inspect_12722cbcebe9  docker_inspect_81c4c81d78ab  docker_inspect_f8f5e90c948b
docker_inspect_16beef48cf20  docker_inspect_97a8d6284cf7  docker_inspect_f90631c51fbb
docker_inspect_26524f88ac2e  docker_inspect_9c3d87daf70a  docker_network_inspect_bridge
docker_inspect_270fe67feaf5  docker_inspect_9dc488133ac0  docker_network_inspect_host
docker_inspect_2f8533794246  docker_inspect_ab9771cb6820  docker_network_inspect_none
docker_inspect_2fb9ddced948  docker_inspect_ae6721cb1792  docker_network_ls
docker_inspect_323545b1e580  docker_inspect_b57757bc2256  docker_ps
docker_inspect_3334d1d9ce6d  docker_inspect_b58e3bd8fc3b  docker_ps_-a
docker_inspect_3c91e8a4777d  docker_inspect_bc8d10fbacf8  docker_stats_--no-stream
docker_inspect_3ef611f378c7  docker_inspect_bc8e502c49ef  docker_version
docker_inspect_4cb9d94ec9a3  docker_inspect_c2e863bf6bfc  journalctl_--no-pager_--unit_docker
docker_inspect_529e41e973c4  docker_inspect_c639b61ba594  ls_-alhR_.etc.docker
~~~

Using the sos 3.4-9

**Comment by iranzo** [comment] 2018-01-25 23:17
Do we have someone to ask about if there's something specific for docker (which I doubt) for this?

If not, I think moving the way forward on checking the rpmdb folders on the host would be the easiest one.

**Comment by TurboTurtle** [comment] 2018-07-31 21:06
I don't think this is a valuable collection point.

First, I can't recall a single time I've needed to look at a container's installed rpm set. The layer information from `docker inspect` can at least provide confirmation of if an image was built from a specific base image or not, after which it is the image that should be looked at, not the container (see below). 

But beyond that though there are some other concerns:

- The example file path is _only_ valid for installations using overlay2. We would not be able to collect this information on any other storage backend (unless we use some ugly invocation of `docker exec` which is an entirely separate can of worms).
    - We'd need to add storage backend detection in at least the `docker` plugin, which if there are daemon issues would likely break.
    - Also, we'd need to handle if we do this collection for stopped/exited containers? Even if that becomes optional, on orchestration platforms this could amount to literally _hundreds_ of rpm calls.

- The above is also _only_ valid for the docker runtime. If we were to commit to collecting a container's rpm data we would need to be able to do it for other runtimes. We'd likely start introducing schisms in consistency of what is collected otherwise.

- When there are issues with a container's installed packages, the focus should transition to the image and not the container itself (i.e. the `buildah` build procedure or a `Dockerfile`) since the container is ephemeral by design, the image is where any kind of persistence would come into play. I don't see the troubleshooting benefit of collecting information from what amounts to the wrong place to be looking.

**Comment by bmr-cymru** [comment] 2018-08-01 09:25
I'm sticking to my original argument: given the variety of containers (e.g. it is in principal possible for a container running on Red Hat to be using dpkg), it's not reasonable for us to try to handle this in sos - as @TurboTurtle points out, the different runtimes, storage backends are too varied for us to be able to reasonably handle them.

**Comment by TurboTurtle** [comment] 2019-04-03 17:08
Closing this request. I do not see this as a thing for sos to reasonably try to handle.

**Closed by TurboTurtle** 2019-04-03 17:08 UTC
