### ISSUE TITLE
Sos report "Too many levels of symbolic links" exception

### ISSUE THREAD

**Issue by npinaeva** [sosreport/sos#2773] opened 2021-12-01 13:16 UTC
I was testing sos report on OCP node and got this exception:
```
Traceback (most recent call last):
  File "/sos/sos/report/__init__.py", line 970, in setup
    plug.setup()
  File "/sos/sos/report/plugins/system.py", line 25, in setup
    "/etc/environment",
  File "/sos/sos/report/plugins/__init__.py", line 1462, in add_copy_spec
    files = self._expand_copy_spec(copyspec)
  File "/sos/sos/report/plugins/__init__.py", line 2616, in _expand_copy_spec
    recursed_files.extend(__expand(os.path.join(_path, '*')))
  File "/sos/sos/report/plugins/__init__.py", line 2590, in __expand
    elif self.path_isdir(path) and self.listdir(path):
  File "/sos/sos/report/plugins/__init__.py", line 2874, in listdir
    return listdir(path, self.sysroot)
  File "/sos/sos/utilities.py", line 247, in listdir
    return _os_wrapper(path, sysroot, 'listdir', os)
  File "/sos/sos/utilities.py", line 227, in _os_wrapper
    return _meth(path)
OSError: [Errno 40] Too many levels of symbolic links: '/host/proc/sys/fs/binfmt_misc'
```
That's all from `sos_logs/system-plugin-errors.txt`. Sos was running inside toolbox, cloned from the main branch, last commit 9596473d1779b9c48e9923c220aaf2b8d9b3bebf

**Comment by pmoravec** [comment] 2021-12-01 14:41
What sysroot or mounting points do you use for the container? When trying to mimic it in a single container, I get different (more fatal) error:

Having upstream `sos` in `/root/sos-main` and mouting it to `/home` (just for a test):

    podman pull ubi8/ubi
    podman run -it --mount=type=bind,src=/root/sos-main,dst=/home,relabel=shared ubi8/ubi /bin/bash
    cd home
    /usr/libexec/platform-python3.6 bin/sos report -o system --batch
    Could not initialize 'report': local variable '_host_sysroot' referenced before assignment

**Comment by TurboTurtle** [comment] 2021-12-01 15:21
> When trying to mimic it in a single container, I get different (more fatal) error:

This is due to not setting the `HOST` env var to the mount point of the host's `/`. 

> That's all from sos_logs/system-plugin-errors.txt. Sos was running inside toolbox, cloned from the main branch, last commit 9596473

For both the sysroot PR and now, I've run sos inside a podman container several times and I can't reproduce this failure.

How exactly does toolbox setup the container? For my tests on the sysroot changes, I was using the support-tools container via `podman container runlabel RUN registry.redhat.io/rhel8/support-tools`, which uses the command specified in the image's `RUN` label. Perhaps there's some difference between that and what toolbox is doing?

**Comment by TurboTurtle** [comment] 2021-12-15 16:57
I was able to see this in an OCP cluster when running `sos` in a container set up by `toolbox`. For reference, toolbox here **is** using the `support-tools` container image as a base.

However, I don't think this is an sos issue. Still within the `toolbox` container, we get the same error when trying a simple `ls`:

~~~
# ls -alh /host/proc/sys/fs/
ls: cannot access '/host/proc/sys/fs/binfmt_misc': Too many levels of symbolic links
total 0
dr-xr-xr-x. 1 root root 0 Dec  7 04:59 .
dr-xr-xr-x. 1 root root 0 Dec  7 04:59 ..
-rw-r--r--. 1 root root 0 Dec 15 16:42 aio-max-nr
-r--r--r--. 1 root root 0 Dec 15 16:42 aio-nr
d?????????? ? ?    ?    ?            ? binfmt_misc
~~~

But, if I start a `support-tools` container via `podman container runlabel RUN` - all is well:

~~~
# podman container runlabel RUN registry.redhat.io/rhel8/support-tools
[root@master-0 /]# ls -alh /host/proc/sys/fs
total 0
dr-xr-xr-x. 1 root root 0 Dec  7 04:59 .
dr-xr-xr-x. 1 root root 0 Dec  7 04:59 ..
-rw-r--r--. 1 root root 0 Dec 15 16:42 aio-max-nr
-r--r--r--. 1 root root 0 Dec 15 16:42 aio-nr
drwxr-xr-x. 2 root root 0 Dec 15 16:16 binfmt_misc
~~~


So this seems more to do with how `toolbox` is using the container image, rather than something in `sos` or even in the `support-tools` image directly.

**Comment by TurboTurtle** [comment] 2022-01-25 18:02
Closing this as this appears to be due to the underlying runtime or image, not sos directly.

For more information/tracking, see https://bugzilla.redhat.com/show_bug.cgi?id=2033365

**Closed by TurboTurtle** 2022-01-25 18:02 UTC
